/*
 * generated by Xtext 2.11.0
 */
package dk.sdu.mdsd.ann.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAnnScopeProvider extends DelegatingScopeProvider {
}
