/*
 * generated by Xtext 2.11.0
 */
package dk.sdu.mdsd.ann



/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class AnnRuntimeModule extends AbstractAnnRuntimeModule {
	
}



