/*
 * generated by Xtext 2.11.0
 */
package dk.sdu.mdsd.ann


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AnnStandaloneSetup extends AnnStandaloneSetupGenerated {

	def static void doSetup() {
		new AnnStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
