/*
 * generated by Xtext 2.11.0
 */
package dk.sdu.mdsd.ann.tests

import com.google.inject.Inject
import dk.sdu.mdsd.ann.ann.ANNModel
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(AnnInjectorProvider)
class AnnParsingTest {
	@Inject
	ParseHelper<ANNModel> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
