/*
 * generated by Xtext 2.11.0
 */
package dk.sdu.mdsd.ann.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class AnnUiModule extends AbstractAnnUiModule {
}
