/**
 * generated by Xtext 2.11.0
 */
package dk.sdu.mdsd.ann.ann;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ANN Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mdsd.ann.ann.ANNModel#getName <em>Name</em>}</li>
 *   <li>{@link dk.sdu.mdsd.ann.ann.ANNModel#getAlpha <em>Alpha</em>}</li>
 *   <li>{@link dk.sdu.mdsd.ann.ann.ANNModel#getEpochs <em>Epochs</em>}</li>
 *   <li>{@link dk.sdu.mdsd.ann.ann.ANNModel#getActivation <em>Activation</em>}</li>
 *   <li>{@link dk.sdu.mdsd.ann.ann.ANNModel#getLayer <em>Layer</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mdsd.ann.ann.AnnPackage#getANNModel()
 * @model
 * @generated
 */
public interface ANNModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see dk.sdu.mdsd.ann.ann.AnnPackage#getANNModel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.ann.ann.ANNModel#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Alpha</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alpha</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alpha</em>' attribute.
   * @see #setAlpha(String)
   * @see dk.sdu.mdsd.ann.ann.AnnPackage#getANNModel_Alpha()
   * @model
   * @generated
   */
  String getAlpha();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.ann.ann.ANNModel#getAlpha <em>Alpha</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alpha</em>' attribute.
   * @see #getAlpha()
   * @generated
   */
  void setAlpha(String value);

  /**
   * Returns the value of the '<em><b>Epochs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Epochs</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Epochs</em>' attribute.
   * @see #setEpochs(int)
   * @see dk.sdu.mdsd.ann.ann.AnnPackage#getANNModel_Epochs()
   * @model
   * @generated
   */
  int getEpochs();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.ann.ann.ANNModel#getEpochs <em>Epochs</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Epochs</em>' attribute.
   * @see #getEpochs()
   * @generated
   */
  void setEpochs(int value);

  /**
   * Returns the value of the '<em><b>Activation</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mdsd.ann.ann.Activation}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Activation</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Activation</em>' containment reference list.
   * @see dk.sdu.mdsd.ann.ann.AnnPackage#getANNModel_Activation()
   * @model containment="true"
   * @generated
   */
  EList<Activation> getActivation();

  /**
   * Returns the value of the '<em><b>Layer</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mdsd.ann.ann.Layer}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Layer</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Layer</em>' containment reference list.
   * @see dk.sdu.mdsd.ann.ann.AnnPackage#getANNModel_Layer()
   * @model containment="true"
   * @generated
   */
  EList<Layer> getLayer();

} // ANNModel
