/**
 * generated by Xtext 2.11.0
 */
package dk.sdu.mdsd.ann.ann;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see dk.sdu.mdsd.ann.ann.AnnFactory
 * @model kind="package"
 * @generated
 */
public interface AnnPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "ann";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.sdu.dk/mdsd/ann/Ann";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "ann";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AnnPackage eINSTANCE = dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl.init();

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.ANNModelImpl <em>ANN Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.ANNModelImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getANNModel()
   * @generated
   */
  int ANN_MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANN_MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Alpha</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANN_MODEL__ALPHA = 1;

  /**
   * The feature id for the '<em><b>Epochs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANN_MODEL__EPOCHS = 2;

  /**
   * The feature id for the '<em><b>Activation</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANN_MODEL__ACTIVATION = 3;

  /**
   * The feature id for the '<em><b>Layer</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANN_MODEL__LAYER = 4;

  /**
   * The number of structural features of the '<em>ANN Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANN_MODEL_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.LayerImpl <em>Layer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.LayerImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getLayer()
   * @generated
   */
  int LAYER = 1;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER__SIZE = 0;

  /**
   * The number of structural features of the '<em>Layer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.HiddenImpl <em>Hidden</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.HiddenImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getHidden()
   * @generated
   */
  int HIDDEN = 2;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HIDDEN__SIZE = LAYER__SIZE;

  /**
   * The feature id for the '<em><b>Lrule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HIDDEN__LRULE = LAYER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Hidden</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HIDDEN_FEATURE_COUNT = LAYER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.InputImpl <em>Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.InputImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getInput()
   * @generated
   */
  int INPUT = 3;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__SIZE = LAYER__SIZE;

  /**
   * The number of structural features of the '<em>Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_FEATURE_COUNT = LAYER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.OutputImpl <em>Output</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.OutputImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getOutput()
   * @generated
   */
  int OUTPUT = 4;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT__SIZE = LAYER__SIZE;

  /**
   * The feature id for the '<em><b>Lrule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT__LRULE = LAYER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Output</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT_FEATURE_COUNT = LAYER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.LearningRuleImpl <em>Learning Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.LearningRuleImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getLearningRule()
   * @generated
   */
  int LEARNING_RULE = 5;

  /**
   * The feature id for the '<em><b>Sigmoid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEARNING_RULE__SIGMOID = 0;

  /**
   * The feature id for the '<em><b>Tansig</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEARNING_RULE__TANSIG = 1;

  /**
   * The feature id for the '<em><b>Named Function</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEARNING_RULE__NAMED_FUNCTION = 2;

  /**
   * The number of structural features of the '<em>Learning Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEARNING_RULE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.ActivationImpl <em>Activation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.ActivationImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getActivation()
   * @generated
   */
  int ACTIVATION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIVATION__NAME = 0;

  /**
   * The number of structural features of the '<em>Activation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIVATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.ExternalImpl <em>External</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.ExternalImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getExternal()
   * @generated
   */
  int EXTERNAL = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTERNAL__NAME = ACTIVATION__NAME;

  /**
   * The number of structural features of the '<em>External</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTERNAL_FEATURE_COUNT = ACTIVATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.CustomImpl <em>Custom</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.CustomImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getCustom()
   * @generated
   */
  int CUSTOM = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOM__NAME = ACTIVATION__NAME;

  /**
   * The feature id for the '<em><b>Input</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOM__INPUT = ACTIVATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOM__EXP = ACTIVATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Der</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOM__DER = ACTIVATION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Custom</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOM_FEATURE_COUNT = ACTIVATION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.ExpressionImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 9;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.MathImpl <em>Math</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.MathImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getMath()
   * @generated
   */
  int MATH = 10;

  /**
   * The number of structural features of the '<em>Math</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATH_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.EulerImpl <em>Euler</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.EulerImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getEuler()
   * @generated
   */
  int EULER = 11;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EULER__VALUE = MATH_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Euler</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EULER_FEATURE_COUNT = MATH_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.NLogImpl <em>NLog</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.NLogImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getNLog()
   * @generated
   */
  int NLOG = 12;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NLOG__VALUE = MATH_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>NLog</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NLOG_FEATURE_COUNT = MATH_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.SinImpl <em>Sin</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.SinImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getSin()
   * @generated
   */
  int SIN = 13;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIN__VALUE = MATH_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Sin</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIN_FEATURE_COUNT = MATH_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.CosImpl <em>Cos</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.CosImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getCos()
   * @generated
   */
  int COS = 14;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COS__VALUE = MATH_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Cos</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COS_FEATURE_COUNT = MATH_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.SqrtImpl <em>Sqrt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.SqrtImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getSqrt()
   * @generated
   */
  int SQRT = 15;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SQRT__VALUE = MATH_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Sqrt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SQRT_FEATURE_COUNT = MATH_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.PowerImpl <em>Power</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.PowerImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getPower()
   * @generated
   */
  int POWER = 16;

  /**
   * The feature id for the '<em><b>Base</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POWER__BASE = MATH_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Exponent</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POWER__EXPONENT = MATH_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Power</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POWER_FEATURE_COUNT = MATH_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.OperandImpl <em>Operand</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.OperandImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getOperand()
   * @generated
   */
  int OPERAND = 18;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERAND__OPERATOR = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERAND__VALUE = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Operand</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERAND_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.NumberLiteralImpl <em>Number Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.NumberLiteralImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getNumberLiteral()
   * @generated
   */
  int NUMBER_LITERAL = 17;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_LITERAL__OPERATOR = OPERAND__OPERATOR;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_LITERAL__VALUE = OPERAND__VALUE;

  /**
   * The number of structural features of the '<em>Number Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_LITERAL_FEATURE_COUNT = OPERAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.LetterImpl <em>Letter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.LetterImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getLetter()
   * @generated
   */
  int LETTER = 19;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LETTER__OPERATOR = OPERAND__OPERATOR;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LETTER__VALUE = OPERAND__VALUE;

  /**
   * The number of structural features of the '<em>Letter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LETTER_FEATURE_COUNT = OPERAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.PartImpl <em>Part</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.PartImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getPart()
   * @generated
   */
  int PART = 20;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PART__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PART__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PART__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Part</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PART_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.ann.ann.impl.FacImpl <em>Fac</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.ann.ann.impl.FacImpl
   * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getFac()
   * @generated
   */
  int FAC = 21;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAC__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAC__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAC__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Fac</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FAC_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.ANNModel <em>ANN Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ANN Model</em>'.
   * @see dk.sdu.mdsd.ann.ann.ANNModel
   * @generated
   */
  EClass getANNModel();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.ann.ann.ANNModel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.mdsd.ann.ann.ANNModel#getName()
   * @see #getANNModel()
   * @generated
   */
  EAttribute getANNModel_Name();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.ann.ann.ANNModel#getAlpha <em>Alpha</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alpha</em>'.
   * @see dk.sdu.mdsd.ann.ann.ANNModel#getAlpha()
   * @see #getANNModel()
   * @generated
   */
  EAttribute getANNModel_Alpha();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.ann.ann.ANNModel#getEpochs <em>Epochs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Epochs</em>'.
   * @see dk.sdu.mdsd.ann.ann.ANNModel#getEpochs()
   * @see #getANNModel()
   * @generated
   */
  EAttribute getANNModel_Epochs();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.mdsd.ann.ann.ANNModel#getActivation <em>Activation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Activation</em>'.
   * @see dk.sdu.mdsd.ann.ann.ANNModel#getActivation()
   * @see #getANNModel()
   * @generated
   */
  EReference getANNModel_Activation();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.mdsd.ann.ann.ANNModel#getLayer <em>Layer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Layer</em>'.
   * @see dk.sdu.mdsd.ann.ann.ANNModel#getLayer()
   * @see #getANNModel()
   * @generated
   */
  EReference getANNModel_Layer();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.Layer <em>Layer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layer</em>'.
   * @see dk.sdu.mdsd.ann.ann.Layer
   * @generated
   */
  EClass getLayer();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.ann.ann.Layer#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size</em>'.
   * @see dk.sdu.mdsd.ann.ann.Layer#getSize()
   * @see #getLayer()
   * @generated
   */
  EAttribute getLayer_Size();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.Hidden <em>Hidden</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hidden</em>'.
   * @see dk.sdu.mdsd.ann.ann.Hidden
   * @generated
   */
  EClass getHidden();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.ann.ann.Hidden#getL_rule <em>Lrule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lrule</em>'.
   * @see dk.sdu.mdsd.ann.ann.Hidden#getL_rule()
   * @see #getHidden()
   * @generated
   */
  EReference getHidden_L_rule();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.Input <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input</em>'.
   * @see dk.sdu.mdsd.ann.ann.Input
   * @generated
   */
  EClass getInput();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.Output <em>Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Output</em>'.
   * @see dk.sdu.mdsd.ann.ann.Output
   * @generated
   */
  EClass getOutput();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.ann.ann.Output#getL_rule <em>Lrule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lrule</em>'.
   * @see dk.sdu.mdsd.ann.ann.Output#getL_rule()
   * @see #getOutput()
   * @generated
   */
  EReference getOutput_L_rule();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.LearningRule <em>Learning Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Learning Rule</em>'.
   * @see dk.sdu.mdsd.ann.ann.LearningRule
   * @generated
   */
  EClass getLearningRule();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.ann.ann.LearningRule#isSigmoid <em>Sigmoid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sigmoid</em>'.
   * @see dk.sdu.mdsd.ann.ann.LearningRule#isSigmoid()
   * @see #getLearningRule()
   * @generated
   */
  EAttribute getLearningRule_Sigmoid();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.ann.ann.LearningRule#isTansig <em>Tansig</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tansig</em>'.
   * @see dk.sdu.mdsd.ann.ann.LearningRule#isTansig()
   * @see #getLearningRule()
   * @generated
   */
  EAttribute getLearningRule_Tansig();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.mdsd.ann.ann.LearningRule#getNamedFunction <em>Named Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Named Function</em>'.
   * @see dk.sdu.mdsd.ann.ann.LearningRule#getNamedFunction()
   * @see #getLearningRule()
   * @generated
   */
  EReference getLearningRule_NamedFunction();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.Activation <em>Activation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Activation</em>'.
   * @see dk.sdu.mdsd.ann.ann.Activation
   * @generated
   */
  EClass getActivation();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.ann.ann.Activation#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.mdsd.ann.ann.Activation#getName()
   * @see #getActivation()
   * @generated
   */
  EAttribute getActivation_Name();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.External <em>External</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>External</em>'.
   * @see dk.sdu.mdsd.ann.ann.External
   * @generated
   */
  EClass getExternal();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.Custom <em>Custom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Custom</em>'.
   * @see dk.sdu.mdsd.ann.ann.Custom
   * @generated
   */
  EClass getCustom();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.ann.ann.Custom#getInput <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Input</em>'.
   * @see dk.sdu.mdsd.ann.ann.Custom#getInput()
   * @see #getCustom()
   * @generated
   */
  EReference getCustom_Input();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.ann.ann.Custom#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see dk.sdu.mdsd.ann.ann.Custom#getExp()
   * @see #getCustom()
   * @generated
   */
  EReference getCustom_Exp();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.ann.ann.Custom#getDer <em>Der</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Der</em>'.
   * @see dk.sdu.mdsd.ann.ann.Custom#getDer()
   * @see #getCustom()
   * @generated
   */
  EReference getCustom_Der();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see dk.sdu.mdsd.ann.ann.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.Math <em>Math</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Math</em>'.
   * @see dk.sdu.mdsd.ann.ann.Math
   * @generated
   */
  EClass getMath();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.Euler <em>Euler</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Euler</em>'.
   * @see dk.sdu.mdsd.ann.ann.Euler
   * @generated
   */
  EClass getEuler();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.ann.ann.Euler#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see dk.sdu.mdsd.ann.ann.Euler#getValue()
   * @see #getEuler()
   * @generated
   */
  EReference getEuler_Value();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.NLog <em>NLog</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>NLog</em>'.
   * @see dk.sdu.mdsd.ann.ann.NLog
   * @generated
   */
  EClass getNLog();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.ann.ann.NLog#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see dk.sdu.mdsd.ann.ann.NLog#getValue()
   * @see #getNLog()
   * @generated
   */
  EReference getNLog_Value();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.Sin <em>Sin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sin</em>'.
   * @see dk.sdu.mdsd.ann.ann.Sin
   * @generated
   */
  EClass getSin();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.ann.ann.Sin#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see dk.sdu.mdsd.ann.ann.Sin#getValue()
   * @see #getSin()
   * @generated
   */
  EReference getSin_Value();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.Cos <em>Cos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cos</em>'.
   * @see dk.sdu.mdsd.ann.ann.Cos
   * @generated
   */
  EClass getCos();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.ann.ann.Cos#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see dk.sdu.mdsd.ann.ann.Cos#getValue()
   * @see #getCos()
   * @generated
   */
  EReference getCos_Value();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.Sqrt <em>Sqrt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sqrt</em>'.
   * @see dk.sdu.mdsd.ann.ann.Sqrt
   * @generated
   */
  EClass getSqrt();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.ann.ann.Sqrt#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see dk.sdu.mdsd.ann.ann.Sqrt#getValue()
   * @see #getSqrt()
   * @generated
   */
  EReference getSqrt_Value();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.Power <em>Power</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Power</em>'.
   * @see dk.sdu.mdsd.ann.ann.Power
   * @generated
   */
  EClass getPower();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.ann.ann.Power#getBase <em>Base</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Base</em>'.
   * @see dk.sdu.mdsd.ann.ann.Power#getBase()
   * @see #getPower()
   * @generated
   */
  EReference getPower_Base();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.ann.ann.Power#getExponent <em>Exponent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exponent</em>'.
   * @see dk.sdu.mdsd.ann.ann.Power#getExponent()
   * @see #getPower()
   * @generated
   */
  EReference getPower_Exponent();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.NumberLiteral <em>Number Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number Literal</em>'.
   * @see dk.sdu.mdsd.ann.ann.NumberLiteral
   * @generated
   */
  EClass getNumberLiteral();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.Operand <em>Operand</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operand</em>'.
   * @see dk.sdu.mdsd.ann.ann.Operand
   * @generated
   */
  EClass getOperand();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.ann.ann.Operand#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see dk.sdu.mdsd.ann.ann.Operand#getOperator()
   * @see #getOperand()
   * @generated
   */
  EAttribute getOperand_Operator();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.ann.ann.Operand#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see dk.sdu.mdsd.ann.ann.Operand#getValue()
   * @see #getOperand()
   * @generated
   */
  EAttribute getOperand_Value();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.Letter <em>Letter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Letter</em>'.
   * @see dk.sdu.mdsd.ann.ann.Letter
   * @generated
   */
  EClass getLetter();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.Part <em>Part</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Part</em>'.
   * @see dk.sdu.mdsd.ann.ann.Part
   * @generated
   */
  EClass getPart();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.ann.ann.Part#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mdsd.ann.ann.Part#getLeft()
   * @see #getPart()
   * @generated
   */
  EReference getPart_Left();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.ann.ann.Part#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see dk.sdu.mdsd.ann.ann.Part#getOperator()
   * @see #getPart()
   * @generated
   */
  EAttribute getPart_Operator();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.ann.ann.Part#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mdsd.ann.ann.Part#getRight()
   * @see #getPart()
   * @generated
   */
  EReference getPart_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.ann.ann.Fac <em>Fac</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fac</em>'.
   * @see dk.sdu.mdsd.ann.ann.Fac
   * @generated
   */
  EClass getFac();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.ann.ann.Fac#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mdsd.ann.ann.Fac#getLeft()
   * @see #getFac()
   * @generated
   */
  EReference getFac_Left();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.ann.ann.Fac#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see dk.sdu.mdsd.ann.ann.Fac#getOperator()
   * @see #getFac()
   * @generated
   */
  EAttribute getFac_Operator();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.ann.ann.Fac#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mdsd.ann.ann.Fac#getRight()
   * @see #getFac()
   * @generated
   */
  EReference getFac_Right();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AnnFactory getAnnFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.ANNModelImpl <em>ANN Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.ANNModelImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getANNModel()
     * @generated
     */
    EClass ANN_MODEL = eINSTANCE.getANNModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ANN_MODEL__NAME = eINSTANCE.getANNModel_Name();

    /**
     * The meta object literal for the '<em><b>Alpha</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ANN_MODEL__ALPHA = eINSTANCE.getANNModel_Alpha();

    /**
     * The meta object literal for the '<em><b>Epochs</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ANN_MODEL__EPOCHS = eINSTANCE.getANNModel_Epochs();

    /**
     * The meta object literal for the '<em><b>Activation</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ANN_MODEL__ACTIVATION = eINSTANCE.getANNModel_Activation();

    /**
     * The meta object literal for the '<em><b>Layer</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ANN_MODEL__LAYER = eINSTANCE.getANNModel_Layer();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.LayerImpl <em>Layer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.LayerImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getLayer()
     * @generated
     */
    EClass LAYER = eINSTANCE.getLayer();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LAYER__SIZE = eINSTANCE.getLayer_Size();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.HiddenImpl <em>Hidden</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.HiddenImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getHidden()
     * @generated
     */
    EClass HIDDEN = eINSTANCE.getHidden();

    /**
     * The meta object literal for the '<em><b>Lrule</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HIDDEN__LRULE = eINSTANCE.getHidden_L_rule();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.InputImpl <em>Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.InputImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getInput()
     * @generated
     */
    EClass INPUT = eINSTANCE.getInput();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.OutputImpl <em>Output</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.OutputImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getOutput()
     * @generated
     */
    EClass OUTPUT = eINSTANCE.getOutput();

    /**
     * The meta object literal for the '<em><b>Lrule</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OUTPUT__LRULE = eINSTANCE.getOutput_L_rule();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.LearningRuleImpl <em>Learning Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.LearningRuleImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getLearningRule()
     * @generated
     */
    EClass LEARNING_RULE = eINSTANCE.getLearningRule();

    /**
     * The meta object literal for the '<em><b>Sigmoid</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LEARNING_RULE__SIGMOID = eINSTANCE.getLearningRule_Sigmoid();

    /**
     * The meta object literal for the '<em><b>Tansig</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LEARNING_RULE__TANSIG = eINSTANCE.getLearningRule_Tansig();

    /**
     * The meta object literal for the '<em><b>Named Function</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEARNING_RULE__NAMED_FUNCTION = eINSTANCE.getLearningRule_NamedFunction();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.ActivationImpl <em>Activation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.ActivationImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getActivation()
     * @generated
     */
    EClass ACTIVATION = eINSTANCE.getActivation();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTIVATION__NAME = eINSTANCE.getActivation_Name();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.ExternalImpl <em>External</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.ExternalImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getExternal()
     * @generated
     */
    EClass EXTERNAL = eINSTANCE.getExternal();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.CustomImpl <em>Custom</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.CustomImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getCustom()
     * @generated
     */
    EClass CUSTOM = eINSTANCE.getCustom();

    /**
     * The meta object literal for the '<em><b>Input</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CUSTOM__INPUT = eINSTANCE.getCustom_Input();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CUSTOM__EXP = eINSTANCE.getCustom_Exp();

    /**
     * The meta object literal for the '<em><b>Der</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CUSTOM__DER = eINSTANCE.getCustom_Der();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.ExpressionImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.MathImpl <em>Math</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.MathImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getMath()
     * @generated
     */
    EClass MATH = eINSTANCE.getMath();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.EulerImpl <em>Euler</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.EulerImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getEuler()
     * @generated
     */
    EClass EULER = eINSTANCE.getEuler();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EULER__VALUE = eINSTANCE.getEuler_Value();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.NLogImpl <em>NLog</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.NLogImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getNLog()
     * @generated
     */
    EClass NLOG = eINSTANCE.getNLog();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NLOG__VALUE = eINSTANCE.getNLog_Value();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.SinImpl <em>Sin</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.SinImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getSin()
     * @generated
     */
    EClass SIN = eINSTANCE.getSin();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIN__VALUE = eINSTANCE.getSin_Value();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.CosImpl <em>Cos</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.CosImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getCos()
     * @generated
     */
    EClass COS = eINSTANCE.getCos();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COS__VALUE = eINSTANCE.getCos_Value();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.SqrtImpl <em>Sqrt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.SqrtImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getSqrt()
     * @generated
     */
    EClass SQRT = eINSTANCE.getSqrt();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SQRT__VALUE = eINSTANCE.getSqrt_Value();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.PowerImpl <em>Power</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.PowerImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getPower()
     * @generated
     */
    EClass POWER = eINSTANCE.getPower();

    /**
     * The meta object literal for the '<em><b>Base</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference POWER__BASE = eINSTANCE.getPower_Base();

    /**
     * The meta object literal for the '<em><b>Exponent</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference POWER__EXPONENT = eINSTANCE.getPower_Exponent();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.NumberLiteralImpl <em>Number Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.NumberLiteralImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getNumberLiteral()
     * @generated
     */
    EClass NUMBER_LITERAL = eINSTANCE.getNumberLiteral();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.OperandImpl <em>Operand</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.OperandImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getOperand()
     * @generated
     */
    EClass OPERAND = eINSTANCE.getOperand();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERAND__OPERATOR = eINSTANCE.getOperand_Operator();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERAND__VALUE = eINSTANCE.getOperand_Value();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.LetterImpl <em>Letter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.LetterImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getLetter()
     * @generated
     */
    EClass LETTER = eINSTANCE.getLetter();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.PartImpl <em>Part</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.PartImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getPart()
     * @generated
     */
    EClass PART = eINSTANCE.getPart();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PART__LEFT = eINSTANCE.getPart_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PART__OPERATOR = eINSTANCE.getPart_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PART__RIGHT = eINSTANCE.getPart_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.ann.ann.impl.FacImpl <em>Fac</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.ann.ann.impl.FacImpl
     * @see dk.sdu.mdsd.ann.ann.impl.AnnPackageImpl#getFac()
     * @generated
     */
    EClass FAC = eINSTANCE.getFac();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FAC__LEFT = eINSTANCE.getFac_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FAC__OPERATOR = eINSTANCE.getFac_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FAC__RIGHT = eINSTANCE.getFac_Right();

  }

} //AnnPackage
