/**
 * generated by Xtext 2.11.0
 */
package dk.sdu.mdsd.ann.ann;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Learning Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mdsd.ann.ann.LearningRule#isSigmoid <em>Sigmoid</em>}</li>
 *   <li>{@link dk.sdu.mdsd.ann.ann.LearningRule#isTansig <em>Tansig</em>}</li>
 *   <li>{@link dk.sdu.mdsd.ann.ann.LearningRule#getNamedFunction <em>Named Function</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mdsd.ann.ann.AnnPackage#getLearningRule()
 * @model
 * @generated
 */
public interface LearningRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Sigmoid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sigmoid</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sigmoid</em>' attribute.
   * @see #setSigmoid(boolean)
   * @see dk.sdu.mdsd.ann.ann.AnnPackage#getLearningRule_Sigmoid()
   * @model
   * @generated
   */
  boolean isSigmoid();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.ann.ann.LearningRule#isSigmoid <em>Sigmoid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sigmoid</em>' attribute.
   * @see #isSigmoid()
   * @generated
   */
  void setSigmoid(boolean value);

  /**
   * Returns the value of the '<em><b>Tansig</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tansig</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tansig</em>' attribute.
   * @see #setTansig(boolean)
   * @see dk.sdu.mdsd.ann.ann.AnnPackage#getLearningRule_Tansig()
   * @model
   * @generated
   */
  boolean isTansig();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.ann.ann.LearningRule#isTansig <em>Tansig</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tansig</em>' attribute.
   * @see #isTansig()
   * @generated
   */
  void setTansig(boolean value);

  /**
   * Returns the value of the '<em><b>Named Function</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Named Function</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Named Function</em>' reference.
   * @see #setNamedFunction(Activation)
   * @see dk.sdu.mdsd.ann.ann.AnnPackage#getLearningRule_NamedFunction()
   * @model
   * @generated
   */
  Activation getNamedFunction();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.ann.ann.LearningRule#getNamedFunction <em>Named Function</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Named Function</em>' reference.
   * @see #getNamedFunction()
   * @generated
   */
  void setNamedFunction(Activation value);

} // LearningRule
