/**
 * generated by Xtext 2.11.0
 */
package dk.sdu.mdsd.ann.ann;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Number Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.mdsd.ann.ann.AnnPackage#getNumberLiteral()
 * @model
 * @generated
 */
public interface NumberLiteral extends Operand
{
} // NumberLiteral
