/*
 * generated by Xtext 2.11.0
 */
package dk.sdu.mdsd.ann.ui;

import com.google.inject.Injector;
import dk.sdu.mdsd.ann.ui.internal.AnnActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AnnExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AnnActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AnnActivator.getInstance().getInjector(AnnActivator.DK_SDU_MDSD_ANN_ANN);
	}
	
}
