/*
 * generated by Xtext 2.11.0
 */
package dk.sdu.mdsd.ann.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AnnAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("dk/sdu/mdsd/ann/parser/antlr/internal/InternalAnn.tokens");
	}
}
