/*
 * generated by Xtext 2.11.0
 */
package dk.sdu.mdsd.ann.ui.tests;

import com.google.inject.Injector;
import dk.sdu.mdsd.ann.ui.internal.AnnActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class AnnUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AnnActivator.getInstance().getInjector("dk.sdu.mdsd.ann.Ann");
	}

}
